language: java

# skip installation step
install: true

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
      env: WITH_COVERALLS=true
    - os: osx
      osx_image: xcode8

script:
 - if [ "$WITH_COVERALLS" == "true" ];
   then
     mvn -f census/pom.xml clean verify -Pjacoco coveralls:report;
   else
     mvn -f census/pom.xml clean verify;
   fi